---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  labels:
    app: productcatalogue
spec:
  type: LoadBalancer
  selector:
    app: productcatalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8020    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogue
  labels:
    app: productcatalogue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productcatalogue
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      containers:
      - name: productcatalogue
        image: 533267044690.dkr.ecr.eu-west-1.amazonaws.com/ecommerce-app-repo:productcatalogue-latest
        ports:
        - containerPort: 8020
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1