---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
  labels:
    app: shopfront
spec:
  type: LoadBalancer
  selector:
    app: shopfront
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8010
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopfront
  labels:
    app: shopfront
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopfront
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - name: shopfront
        image: 533267044690.dkr.ecr.eu-west-1.amazonaws.com/ecommerce-app-repo:shopfront-v2
        ports:
        - containerPort: 8010
        env:
        - name: PRODUCT_CATALOGUE_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-app-config
              key: productcatalogue-url
        - name: STOCK_MANAGER_URL
          valueFrom:
            configMapKeyRef:
              name: ecommerce-app-config
              key: stockmanager-url
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1