---
apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  type: LoadBalancer
  selector:
    app: stockmanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8030       
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stockmanager
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
      - name: stockmanager
        image: 533267044690.dkr.ecr.eu-west-1.amazonaws.com/ecommerce-app-repo:stockmanager-latest
        ports:
        - containerPort: 8030
        # livenessProbe:
          # httpGet:
            # path: /health
            # port: 8030
          # initialDelaySeconds: 30
          # timeoutSeconds: 1